[[redirects]]
  from = "'https://facebookforfriend.netlify.app"
  to = "https://unique-lily-8a3ae4.netlify.app"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"